### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Bread-11** [PopcornColonell/hypnosource#3]
When i try to compile the game i just get this error message 
![4d1c9c2efb03d1e5b8a453ca98f81e9d](https://user-images.githubusercontent.com/63719200/197853291-97caed5f-374f-4ab3-8267-07cb58e63f66.png)
I have tried to edit the code but then i just get other errors

**Comment by MemeHoovy** [comment]
haxelib install flxanimate 1.2.0

**Comment by Bread-11** [comment]
Still doesn't work

**Comment by Cheemsandfriends** [comment]
afaik, it uses some custom flxanimate code?
I think that to fix the issue you would need to just lower the brackets that sorround the function, cos they're like
```haxe
public static function fromSparrow(Path:FlxSparrow, ?Image:FlxGraphicAsset):FlxAtlasFrames
	{
```
instead of
```haxe
public static function fromSparrow(Path:FlxSparrow, ?Image:FlxGraphicAsset):FlxAtlasFrames
{
```
same for the ending bracket, and i think thats it?
tbh idk cos it should work from what ive seen.

idk why yoshubs grabbed the whole folder, i thought she would modify only the "filters shader" file, but whatev

**Comment by REALHaydenGaming** [comment]
[developer will ignore most bug reports](https://twitter.com/Sector0003/status/1584560451391610880?s=20&t=49X-to16URmHOluICDUGKQ)

**Comment by PopcornColonell** [comment]
skill issue lmao

**Comment by davidfnf** [comment]
it wont work still
 it still says the same thing

**Comment by moxie-coder** [comment]
> it wont work still it still says the same thing

skill issue
